### ISSUE TITLE
Position der Faltmarke

### ISSUE THREAD

**Issue by rreben** [mac-and-i/Normbrief-mit-Markdown#1]
Vielen Dank für das tolle Projekt. Leider kenne ich mich mit css nicht gut aus. Wie kann ich die Position der Faltmarke (nach unten) verschieben?

**Comment by mac-and-i** [comment]
Ich hatte damals keine gute Lösung gefunden. Wenn man ein Hintergrundbild verwendet (etwa ein SVG), erscheint es auf jeder Seite, doch nicht immer lässt sich das Drucken von Hintergründen einschalten. Alternativ hatte ich folgendes CSS ausprobiert. Das funktioniert abhängig vom Browser nur auf der ersten Seite und auch die Positionierung scheint nicht immer zu passen.

```css
body::before {
	content: "";
	border-top: 1px solid gray;
	width: 10mm;
	position: fixed;
	top: 105mm;
	left: 0mm;
}

body::after {
	content: "";
	border-top: 1px solid gray;
	width: 10mm;
	position: fixed;
	top: 210mm;
	left: 0mm;
}
```
